name: postgres-cluster-lab

include:
  - path: ./compose/etcd.yaml
    project_directory: .
  - path: ./compose/postgres.yaml
    project_directory: .
  - path: ./compose/haproxy.yaml
    project_directory: .
  - path: ./compose/pgbouncer.yaml
    project_directory: .

networks:
  pgnet:
    driver: bridge

volumes:
  etcd1_data:
  etcd2_data:
  etcd3_data:
  pg_node1_data:
  pg_node2_data:
  pg_node3_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  replication_password:
    file: ./secrets/replication_password.txt
