name: postgres-cluster-lab

services:
  etcd1:
    image: gcr.io/etcd-development/etcd:v3.6.0
    container_name: etcd1
    hostname: etcd1
    command:
      - /usr/local/bin/etcd
      - --name=etcd1
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd1:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=postgres-lab-etcd
    volumes:
      - etcd1_data:/etcd-data
    networks:
      - pgnet
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/etcdctl",
          "--endpoints=http://127.0.0.1:2379",
          "endpoint",
          "health"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  etcd2:
    image: gcr.io/etcd-development/etcd:v3.6.0
    container_name: etcd2
    hostname: etcd2
    command:
      - /usr/local/bin/etcd
      - --name=etcd2
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd2:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=postgres-lab-etcd
    volumes:
      - etcd2_data:/etcd-data
    networks:
      - pgnet
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/etcdctl",
          "--endpoints=http://127.0.0.1:2379",
          "endpoint",
          "health"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  etcd3:
    image: gcr.io/etcd-development/etcd:v3.6.0
    container_name: etcd3
    hostname: etcd3
    command:
      - /usr/local/bin/etcd
      - --name=etcd3
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd3:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd3:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=postgres-lab-etcd
    volumes:
      - etcd3_data:/etcd-data
    networks:
      - pgnet
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/etcdctl",
          "--endpoints=http://127.0.0.1:2379",
          "endpoint",
          "health"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped



  pg-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg-node1
    hostname: pg-node1

    secrets:
      - postgres_password
      - replication_password

    volumes:
      - pg_node1_data:/var/lib/postgresql
      - ./patroni/patroni-node1.yml:/etc/patroni/patroni.yml:ro

    networks:
      - pgnet

    depends_on:
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8008/health >/dev/null || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s


  pg-node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg-node2
    hostname: pg-node2

    secrets:
      - postgres_password
      - replication_password

    volumes:
      - pg_node2_data:/var/lib/postgresql
      - ./patroni/patroni-node2.yml:/etc/patroni/patroni.yml:ro

    networks:
      - pgnet

    depends_on:
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8008/health >/dev/null || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s


  pg-node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg-node3
    hostname: pg-node3

    secrets:
      - postgres_password
      - replication_password    

    volumes:
      - pg_node3_data:/var/lib/postgresql
      - ./patroni/patroni-node3.yml:/etc/patroni/patroni.yml:ro

    networks:
      - pgnet

    depends_on:
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started
      etcd3:
        condition: service_started

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8008/health >/dev/null || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  haproxy:
    image: haproxy:3.2-alpine
    container_name: haproxy
    hostname: haproxy
    depends_on:
      pg-node1:
        condition: service_healthy
      pg-node2:
        condition: service_healthy
      pg-node3:
        condition: service_healthy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "127.0.0.1:8404:8404"
    networks:
      - pgnet
    restart: unless-stopped

  pgbouncer-1:
    image: ghcr.io/icoretech/pgbouncer-docker:1.25.2
    container_name: pgbouncer-1
    hostname: pgbouncer-1
    depends_on:
      haproxy:
        condition: service_started
    entrypoint: ["/usr/local/bin/pgbouncer-entrypoint.sh"]
    volumes:
      - ./pgbouncer/pgbouncer-1.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/entrypoint.sh:/usr/local/bin/pgbouncer-entrypoint.sh:ro
    secrets:
      - postgres_password
    ports:
      - "127.0.0.1:5432:6432"
    networks:
      - pgnet
    restart: unless-stopped

  pgbouncer-2:
    image: ghcr.io/icoretech/pgbouncer-docker:1.25.2
    container_name: pgbouncer-2
    hostname: pgbouncer-2
    depends_on:
      haproxy:
        condition: service_started
    entrypoint: ["/usr/local/bin/pgbouncer-entrypoint.sh"]
    volumes:
      - ./pgbouncer/pgbouncer-2.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/entrypoint.sh:/usr/local/bin/pgbouncer-entrypoint.sh:ro
    secrets:
      - postgres_password
    ports:
      - "127.0.0.1:5433:6432"
    networks:
      - pgnet
    restart: unless-stopped

networks:
  pgnet:
    driver: bridge

volumes:
  etcd1_data:
  etcd2_data:
  etcd3_data:

  pg_node1_data:
  pg_node2_data:
  pg_node3_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  replication_password:
    file: ./secrets/replication_password.txt
